### ISSUE TITLE
https://repo.grails.org/grails/core hardcoded in grails.init.Start

### ISSUE THREAD

**Issue by cosenmarco** [grails/grails-wrapper#5]
Since the old repository is not available any longer (https://repo.grails.org/grails/core) my grails wrapper stopped working. The URL has changed to  https://repo.grails.org/artifactory/core

See https://github.com/grails/grails-core/issues/11825

Unfortunately this older URL is hardcoded in Start.java:
https://github.com/grails/grails-wrapper/blob/master/starter/src/main/java/grails/init/Start.java#L22

**Comment by jeffbrown** [comment]
Related to https://github.com/grails/grails-core/issues/11825.

**Comment by JasonTypesCodes** [comment]
This has been resolved in Grails 4.0.11
